export enum MessageDisplayEvents {
    GET_ALL_MESSAGES = 'GET_ALL_MESSAGES',
    SEND_FILTER = 'SEND_FILTER',
    SEND_FREE_TEXT_FILTER = 'SEND_FREE_TEXT_FILTER',
    REMOVE_FILTER = 'REMOVE_FILTER',
    REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS',
    SELECT_SEGMENT = 'SELECT_SEGMENT',
    SELECT_MESSAGE = 'SELECT_MESSAGE',
    SAVE_VALUE = 'SAVE_VALUE',
    DOWNLOAD_MESSAGE = 'DOWNLOAD_MESSAGE',
    DOWNLOAD_ALL_MESSAGES = 'DOWNLOAD_ALL_MESSAGES'
}